# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171215_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('comment', models.TextField(max_length=1000, verbose_name='评论')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogComment')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog_comment',
            name='article',
        ),
        migrations.DeleteModel(
            name='Blog_Comment',
        ),
    ]
